### ISSUE TITLE
CORS header failure on current live site

### ISSUE THREAD

**Issue by conatus** [BeautifulTrouble/api-docs#1]
Hi all,

On https://beautifulrising.org we are currently seeing CORS header failures, preventing any usage of the site.

<img width="1484" alt="Screenshot 2019-09-04 at 05 22 50" src="https://user-images.githubusercontent.com/317734/64225683-58388b00-ced4-11e9-8c1f-c9a8eadc9369.png">

Probably a very simple fix to add these to allow cross-domain, presumably between https://beautifulrising.org and https://beautifultrouble.org/

**Comment by adrian-the-git** [comment]
I believe this was an outage. Please re-open if this is not solved.

**Comment by conatus** [comment]
It works for me! Thanks!
